backend = "glx";
vsync = true;
detect-rounded-corners = true;
use-damage = true;

#################################
# BLUR SETTINGS (Darker glass)
#################################

blur-method = "dual_kawase";
blur-size = 14;
blur-strength = 12;

blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Xfce4-notifyd'",
];

#################################
# OPACITY (darker windows)
#################################

active-opacity = 0.88;
#inactive-opacity = 0.70;
frame-opacity = 0.80;

#inactive-dim = 0.30;
#inactive-dim-fixed = false;

opacity-rule = [
  "85:class_g = 'kitty'",
  "70:class_g = 'Thunar'",
  "85:class_g = 'xfce4-terminal'",
  "90:class_g = 'code'",
  "90:class_g = 'chromium'",
  "90:class_g = 'Firefox'",
  "85:class_g = 'obsidian'",
  "80:class_g = 'burp-StartBurp'",
];

#################################
# SHADOWS (deep dark shadows)
#################################

shadow = true;
shadow-radius = 22;
shadow-opacity = 0.65;
shadow-offset-x = -12;
shadow-offset-y = -12;

shadow-red = 0.0;
shadow-green = 0.0;
shadow-blue = 0.0;

#################################
# ROUNDED CORNERS
#################################

corner-radius = 10;

#################################
# FADING
#################################

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;
