
#!/bin/bash

# Array of Japanese quotes with English translations
quotes=(
"七転び八起き | Fall seven times, rise eight times - Never give up"
"井の中の蛙大海を知らず | A frog in a well knows not the ocean - Don’t be narrow-minded"
"猿も木から落ちる | Even monkeys fall from trees - Everyone makes mistakes"
"出る杭は打たれる | The nail that sticks out gets hammered - Don’t stand out too much"
"知らぬが仏 | Ignorance is bliss - Sometimes it’s better not to know"
"花より団子 | Dumplings over flowers - Practicality over beauty"
"継続は力なり | Persistence is strength - Keep going to succeed"
"十人十色 | Ten people, ten colors - Everyone has different tastes"
"時は金なり | Time is money - Time is precious"
"負けるが勝ち | There is victory in defeat - Sometimes losing is winning"
"能ある鷹は爪を隠す | A skilled hawk hides its claws - Humble people don’t show off"
"覆水盆に返らず | Spilled water won’t return to the tray - What’s done cannot be undone"
"石の上にも三年 | Three years on a rock - Patience conquers all"
"初心忘れるべからず | Do not forget the beginner’s mind - Stay humble and eager"
"雨降って地固まる | After rain, the ground hardens - Adversity strengthens you"
"虎穴に入らずんば虎子を得ず | No tiger’s cub without entering the tiger’s den - No risk, no reward"
"終わり良ければ全て良し | All’s well that ends well - Keep the end in sight"
"千里の道も一歩から | A journey of a thousand miles begins with a single step - Start now"
"鉄は熱いうちに打て | Strike the iron while hot - Take action at the right moment"
"習うより慣れよ | Practice makes perfect - Learn by doing"
"努力は裏切らない | Effort never betrays - Hard work pays off"
"光陰矢の如し | Time flies like an arrow - Use time wisely"
"一期一会 | Once in a lifetime encounter - Value every meeting"
"夢は叶う | Dreams come true - Believe in your vision"
"明日は明日の風が吹く | Tomorrow will bring its own wind - Don’t worry too much"
"笑う門には福来たる | Fortune enters a smiling home - Positivity attracts happiness"
"船頭多くして船山に登る | Too many captains take the boat up a mountain - Don’t overcomplicate"
"短気は損気 | Short temper is a short gain - Patience saves"
"待てば海路の日和あり | Calm seas come to those who wait - Endurance brings peace"
"誠心誠意 | With true heart and sincerity - Give your all"
"三人寄れば文殊の知恵 | Three together, wisdom of gods - Teamwork multiplies strength"
"努力は必ず報われる | Effort will surely be rewarded - Keep pushing"
"出る杭は伸びる | The nail that sticks out grows - Stand out to shine"
"雲の上はいつも晴れ | Above the clouds, it’s always sunny - Bright times await"
"雨だれ石を穿つ | Dripping water pierces stone - Consistent effort wins"
"負けても勝ち | A loss can be a win - Even setbacks teach"
"行動は言葉に勝る | Actions beat words - Show, don’t tell"
"己を知る者は智なり | Knowing oneself is wisdom - Understand yourself first"
"毎日が新しい一日 | Every day is a new day - Begin fresh daily"
"意志あるところに道あり | Where there is will, there is a way - Determination creates paths"
"塵も積もれば山となる | Even dust piled up becomes a mountain - Small efforts build greatness"
"苦あれば楽あり | After hardship comes ease - Balance in life"
"前を向け | Face forward - Don’t dwell on the past"
"志高く | Aspire high - Aim for greatness"
"今日できることを明日に延ばすな | Don’t postpone today’s work to tomorrow - Act now"
"真心は伝わる | Sincerity reaches others - Be genuine"
"夢見ることは生きること | To dream is to live - Dreams fuel life"
"人事を尽くして天命を待つ | Do your best, then leave it to fate - Give your all"
"七難八苦を越えてこそ | Only after many hardships - Strength is built"
"自分に勝つ | Conquer yourself - True victory is within"
"笑顔は最強の武器 | A smile is the strongest weapon - Win hearts with kindness"
"百聞は一見にしかず | Hearing 100 times is not as good as seeing once - Experience matters"
"石橋を叩いて渡る | Knock before crossing the stone bridge - Careful is safe"
"無理は禁物 | Overdoing is forbidden - Know your limits"
"克己心 | Spirit of self-mastery - Discipline leads to success"
"人生は一度きり | Life is only once - Make it count"
"一歩一歩が力になる | Every step builds strength - Progress is gradual"
"雨の後には虹が出る | After rain comes a rainbow - Good follows bad"
"大器晩成 | Great vessels take time - Greatness needs patience"
"種を蒔かなければ実らぬ | Without sowing seeds, nothing grows - Effort first"
"勇気一つを友として | With courage as your friend - Bravery guides"
"逆境こそチャンス | Adversity is the chance - Difficulties give openings"
"負け犬になるな | Don’t be a loser - Stand tall"
"学べば知る | Learn and you will know - Growth requires learning"
"希望は心の太陽 | Hope is the sun for the heart - Never lose it"
"心静かに | Keep a calm heart - Peace helps progress"
"先んずれば人を制す | The early bird controls the game - Act first"
"苦労は買ってでもせよ | Even buy hardships if you can - Challenges teach"
"知らぬ間に力はつく | Strength grows unnoticed - Consistent work adds up"
"努力して幸運を呼ぶ | Effort calls in luck - Make your own fortune"
"焦らずとも道は開く | Even without rushing, roads open - Trust time"
"石に立つ矢 | An arrow stands in stone - Effort makes miracles"
"心が変われば運命が変わる | Change the heart, change the destiny - Mindset shapes life"
"夢なき者に成功なし | Without dreams, no success - Dream before achieving"
"挑戦なくして成長なし | No challenge, no growth - Take risks to improve"
"涙の数だけ強くなる | Tears make you stronger - Pain builds resilience"
"健全な魂は強い体に宿る | A sound soul dwells in a strong body - Care for yourself"
"努力重ねて未来を掴む | Pile on effort to seize the future - Keep at it"
"素直さは力 | Honesty is power - Stay true"
"初心は宝 | The beginner’s mind is treasure - Cherish fresh vision"
"火のない所に煙は立たぬ | No smoke without fire - Stay mindful"
"受け入れることで進め | By accepting, you move on - Flow with life"
"先のことはわからぬ | The future is unknown - Live today fully"
"深呼吸して前へ | Take a deep breath and move forward - Calm progress"
"一意専心 | Single-minded devotion - Focus brings success"
"自分の道を歩め | Walk your own path - Be authentic"
"人の振り見て我が振り直せ | See others’ ways and fix your own - Learn from others"
"経験は宝 | Experience is treasure - Value life lessons"
"思い立ったが吉日 | The day you think it is lucky - Start without delay"
"諦めは失敗の始まり | Giving up starts failure - Never quit"
"行動なくして成果なし | No action, no result - Move to achieve"
"自分は自分 | You are you - Don’t compare"
"挑戦者であれ | Be a challenger - Take on life boldly"
"幸運は準備した心に訪れる | Luck comes to the prepared mind - Be ready always"
"闇が深ければ星は輝く | The darker the night, the brighter the stars - Hardship shows your strength"
"心配せず信じよ | Don’t worry, believe - Faith matters"
"今がその時 | Now is the moment - Take the chance"
"積み重ねが力 | Accumulation is strength - Small steps count"
"未来は今日で作る | The future is built today - Start shaping it"
"挑む者に道は開く | For challengers, the road opens - Courage unlocks paths"
"心燃やせ | Burn your heart - Live passionately"
"成せば成る | If you try, it will be done - Believe and act"
"継続して強者となれ | Continue and become strong - Persistence wins"
"夢は逃げない | Dreams don’t run away - Chase relentlessly"
"限界は自分が作る | Limits are self-made - Break them"
"流れに逆らえ | Swim against the current - Dare to be different"
"感謝こそ力 | Gratitude is power - Give thanks"
"勇敢に生きろ | Live courageously - Fear nothing"
"己を磨け | Polish yourself - Improve a little every day"
"道は自ら開く | The road opens by itself - Keep walking"
"明けない夜はない | No night lasts forever - Darkness passes"
"平常心是道 | A calm mind is the way - Steady wins"
"一日一善 | One good deed a day - Build goodness daily"
"勇気は連鎖する | Courage is contagious - Inspire others"
"継続こそ王道 | Continuity is the royal road - Keep at it"
"初心貫徹 | Carry through your first intent - Stay the course"
"日々精進 | Daily devotion - Improve relentlessly"
"実るほど頭を垂れる稲穂かな | The ripe ear of rice bows low - Humility with success"
"道は歩くから道になる | A road exists because we walk it - Action creates path"
"不屈不撓 | Indomitable spirit - Never bend, never break"
"先義後利 | Righteousness before profit - Values first"
"心技体 | Mind, skill, body - Balance all three"
"有言実行 | Say and do - Keep promises"
"継続即力 | Continuation is power - Momentum matters"
"日進月歩 | Daily progress, monthly steps - Advance steadily"
"気は心 | Spirit is heart - Attitude shapes outcomes"
"気持ちで負けるな | Don’t lose in spirit - Stay mentally strong"
"捨てる神あれば拾う神あり | One god throws away, another picks up - Help comes"
"苦しい時こそ笑え | Smile especially in hardship - Strength through joy"
"思いは叶う | Thoughts become reality - Envision and act"
"道遠しとも一歩から | However far, start with one step - Begin small"
"自分を信じ切れ | Believe fully in yourself - Trust your core"
"志は高く、足元は堅く | Aim high, stand firm - Dream and ground"
"力は出すほど増える | The more you use strength, the more it grows - Use it"
"挑戦の先に景色あり | There’s a view beyond challenge - Push through"
"未来は意志で変わる | Will changes the future - Decide and move"
"失敗は経験値 | Failure is experience points - Level up"
"心の火を絶やすな | Don’t let your inner fire die - Guard motivation"
"道に迷うは学びの始まり | Getting lost begins learning - Explore boldly"
"積小為大 | Make big by piling small - Small steps"
"誠実は最強の武器 | Sincerity is the strongest weapon - Be honest"
"初心に戻れ | Return to the beginning - Reset to progress"
"準備八割 | Preparation is eighty percent - Ready yourself"
"礼節は力 | Courtesy is power - Respect wins"
"踏み出せば景色が変わる | One step changes the view - Move first"
"志は日々磨け | Polish your aspiration daily - Keep it bright"
"習慣が人生を作る | Habits shape life - Design routines"
"恐れず挑め | Challenge without fear - Bravery first"
"百戦錬磨 | Tempered by a hundred battles - Experience builds steel"
"決断は速く | Decide quickly - Speed matters"
"迷えば途絶える | If you waver, the path breaks - Be decisive"
"手を動かせ | Move your hands - Action over thought"
"努力を楽しめ | Enjoy the effort - Love the grind"
"粘り勝ち | Victory by persistence - Stick with it"
"凡事徹底 | Master the basics - Excellence in essentials"
"志一筋 | Single-minded ambition - Focus tight"
"勝って兜の緒を締めよ | Tighten your helmet after victory - Stay vigilant"
"実行の人であれ | Be a person of action - Do what you say"
"自己超越 | Self-transcendence - Go beyond yourself"
"挑めば扉は開く | If you challenge, doors open - Knock boldly"
"今日の一歩が明日を変える | Today’s step changes tomorrow - Act daily"
"積み上げは裏切らない | What you build won’t betray you - Trust the grind"
"凡を極めて非凡に至る | Master the ordinary to reach extraordinary - Excellence through basics"
"機会は準備に味方する | Opportunity favors the prepared - Be ready"
"志あれば道あり | With aspiration comes a path - Purpose guides"
"歩みを止めるな | Don’t stop walking - Keep moving"
"逆風は追い風に変わる | Headwinds become tailwinds - Endure and turn"
"人生は挑戦の連続 | Life is a chain of challenges - Keep challenging"
"自律は自由の条件 | Discipline is the price of freedom - Control yourself"
"継続で差をつける | Create the gap with consistency - Outlast"
"努力は天才を凌駕する | Effort surpasses genius - Outwork"
"目の前の一歩に全力 | All in on the next step - Focus near"
"積み重ねが自信になる | Accumulation becomes confidence - Build proof"
"覚悟を決めよ | Make up your mind - Commit fully"
"勝負は準備で決まる | Preparation decides the match - Prepare deep"
"自己研鑽を怠るな | Don’t neglect self-cultivation - Keep learning"
"磨けば光る | Polish and it will shine - Develop potential"
"信念は力 | Conviction is power - Believe steadfastly"
"己の弱さを認めよ | Admit your weakness - Then strengthen"
"力は静かに宿る | Power resides quietly - Be steady"
"継続してこそ本物 | Only with continuity comes the real - Keep showing up"
"挑戦は最高の学び | Challenge teaches best - Learn by trying"
"足元を固めよ | Firm up your footing - Build foundations"
"勝機は練習の中にある | Victory is in practice - Train hard"
"準備は裏切らない | Preparation doesn’t betray - Ready wins"
"焦らず狙いを定めよ | Don’t rush, take aim - Accuracy first"
"小さな勝利を重ねよ | Stack small wins - Build momentum"
"一念岩をも通す | One resolve pierces rock - Willpower prevails"
"自分史上最高を更新せよ | Update your personal best - Beat yourself"
"日々挑戦 | Challenge daily - Keep testing limits"
"志は行動で証明 | Prove ambition with action - Show it"
"今日の最善を尽くせ | Do the best of today - Leave nothing"
"可能性は無限 | Possibility is infinite - Keep exploring"
"自分を超える旅 | Journey to surpass yourself - Evolve"
"勝つまでやる | Keep going until you win - Persist to victory"
"心を強く育てよ | Cultivate a strong heart - Train resilience"
"姿勢が運を呼ぶ | Posture attracts luck - Stand ready"
"挑戦者の背中で語れ | Speak with the back of a challenger - Lead by doing"
"踏ん張りどころで粘れ | Hold fast at the critical point - Don’t break"
"変化を恐れるな | Don’t fear change - Adapt boldly"
"逆境は師 | Adversity is a teacher - Learn from pain"
"平凡の積み重ねが非凡 | Ordinary stacked becomes extraordinary - Keep piling"
"努力の天井はない | There’s no ceiling to effort - Keep raising it"
"思考は現実化の起点 | Thought is the start of reality - Think clearly"
"準備で七割勝つ | Win seventy percent with prep - Front-load"
"初心に宿る力 | Power resides in beginners’ mind - Stay fresh"
"結局やる人が強い | In the end, doers are strong - Take action"
"信頼は積み重ね | Trust is built bit by bit - Earn it"
"継続は最強の武器 | Consistency is the strongest weapon - Be steady"
"努力を習慣化せよ | Make effort a habit - Normalize hard work"
"一歩先を読む | Read one step ahead - Anticipate"
"やり抜く力を鍛えよ | Train grit - Finish what you start"
"心を整えよ | Set your mind - Prepare internally"
"覚悟の量が結果を決める | The amount of resolve decides results - Commit deep"
"挑戦する権利は誰にもある | Everyone has the right to challenge - Take the right"
"選択が人生を作る | Choices make life - Choose wisely"
"集中は才能 | Focus is a talent - Hone attention"
"継続に勝る天才なし | No genius beats consistency - Keep going"
"可能性を信じる勇気 | Courage to believe in possibility - Dare to believe"
"負荷こそ成長 | Load equals growth - Embrace difficulty"
"習慣が運命を変える | Habits change destiny - Design daily"
"工夫で突破 | Ingenuity breaks through - Be inventive"
"一歩先へ | One step forward - Keep advancing"
"挑戦の対価は成長 | The price of challenge is growth - Pay it"
"誠実に積む | Build sincerely - Integrity compounds"
"日々鍛錬 | Daily training - Sharpen consistently"
"継続で信頼を得る | Earn trust through consistency - Be reliable"
"努力の痕跡が自信 | Traces of effort become confidence - See your work"
"背中で語る人になれ | Be someone who speaks by their back - Lead quietly"
"誠の力 | The power of truth - Be genuine"
"熱量で押し切れ | Win with heat - Outpassion them"
"結果より過程を磨け | Polish the process over results - Process first"
"失敗の中に答えあり | Answers hide in failure - Study them"
"変化は進化のサイン | Change signals evolution - Embrace it"
"やるべきことをやる | Do what must be done - Duty first"
"本気は伝播する | Seriousness spreads - Elevate the room"
"一呼吸置いてから進め | Take a breath then proceed - Calm action"
"志を言語化せよ | Put your ambition into words - Clarify aims"
"自分との約束を守れ | Keep promises to yourself - Build self-trust"
"努力の総量がものを言う | Total effort speaks loudest - Accumulate"
"挑戦は自尊心を育てる | Challenge grows self-respect - Earn pride"
"凡事を侮るな | Don’t belittle the basics - Respect fundamentals"
"地味な努力が華になる | Quiet effort becomes flower - Bloom later"
"時間は最上の資産 | Time is the best asset - Invest wisely"
"質は量から生まれる | Quality comes from quantity - Produce more"
"準備が自信になる | Preparation turns into confidence - Ready builds belief"
"弱さを抱いて強くなれ | Carry weakness, become strong - Transform"
"誇りは積み重ねから | Pride comes from accumulation - Build merit"
"現状維持は後退 | Status quo is retreat - Keep advancing"
"心の姿勢が結果を呼ぶ | Mental posture calls results - Align inside"
"限界の一歩先へ | One step past the limit - Stretch"
"努力に勝る近道なし | No shortcut beats effort - Accept the path"
"学び続ける者が勝つ | Learners win - Stay curious"
"愚直にやり切れ | Be stubbornly honest and finish - Straightforward grind"
"好機は行動の中に | Opportunity lives in action - Move to find it"
"挑戦の痛みは一時 | Pain of challenge is temporary - Growth remains"
"規律が自由を産む | Discipline produces freedom - Structure unlocks"
"今日を制す | Master today - Own the day"
"勝つ習慣を作れ | Build the habit of winning - Systemize success"
"弱点は伸びしろ | Weakness is room to grow - Train it"
"志を燃やし続けよ | Keep your ambition aflame - Feed the fire"
"賢く、強く、優しく | Smart, strong, kind - Balance virtues"
"積み上げは裏切らない心 | Trust in the pile - Believe your work"
"やり切った先に見える景色 | The view after finishing - Finish to see it"
"やればできるは武器 | ‘Can do’ is a weapon - Use belief"
"誠実に勝る戦略なし | No strategy beats sincerity - Be true"
"挑み続ける者だけが辿り着く | Only those who keep challenging arrive - Endure"
"自分の速度で進め | Advance at your own speed - Sustainable pace"
"足もとを見よ | Watch your step - Mind the present"
"覚悟は才能 | Resolve is a talent - Cultivate it"
"小さな挑戦を積め | Stack small challenges - Scale up"
"焦点を一つに | One focal point - Concentrate"
"丁寧に生きよ | Live carefully - Quality first"
"困難歓迎 | Welcome difficulty - Train in the storm"
"静かに燃えよ | Burn quietly - Inner fire"
"凛として進め | Proceed with dignity - Stay poised"
"努力は嘘をつかない | Effort doesn’t lie - Believe the work"
"真剣に遊べ | Play seriously - Joy with rigor"
"勝てる準備をせよ | Prepare to be able to win - Set the stage"
"挑む心が景色を変える | A challenging heart changes the view - Mindset matters"
"昨日より一歩先へ | One step ahead of yesterday - Continuous upgrade"
"志の火種を守れ | Protect the spark of ambition - Guard purpose"
"静かに積む者が最後に勝つ | Quiet builders win last - Patience wins"
"深く、ゆっくり、確かに | Deeply, slowly, surely - True progress"
"自分の物語を生きよ | Live your own story - Own your path"
"磨き続ければ道は光る | Keep polishing and the path will shine - Persistence illuminates"
"誠意が道を開く | Sincerity opens roads - Heart leads"
"挑戦でしか掴めない景色 | Views only challenge can reach - Climb"
"やると決めたらやる | If decided, do it - No half measures"
"決断の速さは生の濃度 | Fast decisions, dense life - Move briskly"
"努力の臨界点で花が咲く | Flowers bloom at effort’s critical point - Keep pushing"
"期待は自分で超える | Exceed your own expectations - Surprise yourself"
"心の器を広げよ | Widen the vessel of the heart - Grow capacity"
"挑戦が日常 | Make challenge the norm - Normalize growth"
"勝利は準備の副産物 | Victory is a byproduct of preparation - Focus on prep"
"弱さを隠すな、超えよ | Don’t hide weakness, surpass it - Transform openly"
"時間を味方に | Make time an ally - Compound steadily"
"学びを即行動に | Turn learning into action - Apply fast"
"努力の向きを合わせよ | Align the direction of effort - Work on the right things"
"続ける仕組みを作れ | Build systems to continue - Design persistence"
"やらない後悔よりやる後悔 | Regret doing less than not doing - Choose action"
"心が折れそうな時こそ一歩 | One step when the heart breaks - Micro-bravery"
"規律は優しさ | Discipline is kindness - To future self"
"誠を尽くせ | Do your utmost sincerely - Full heart"
"人のために尽くせば道が開く | Serve others and roads open - Contribution creates luck"
"挑戦の先に自分がいる | The self lies beyond challenge - Meet yourself"
"覚悟の深さが景色を変える | Depth of resolve changes scenery - Commit deeper"
"努力を楽しくする工夫 | Make effort fun - Sustain joy"
"反省は短く改善は早く | Reflect briefly, improve quickly - Forward fast"
"一手先へ準備 | Prepare one move ahead - Strategize"
"目の前の人を大切に | Value the person in front - Relationships first"
"誠実な勝利を目指せ | Aim for honest victory - Win clean"
"夢は描き直せる | Dreams can be redrawn - Iterate"
"挑戦の痛みで強化 | Strengthen through challenge pain - Harden"
"苦難を糧に | Make hardship your fuel - Consume trials"
"静かに勝つ | Win quietly - Let results speak"
"全力の基準を上げよ | Raise the standard of full effort - Upgrade output"
"一歩の重みを知れ | Know the weight of one step - Respect progress"
"志を灯し続けよ | Keep the light of ambition lit - Guard flame"
"努力の証拠を残せ | Leave evidence of effort - Track work"
"挑戦の記録を積め | Accumulate challenge records - Build history"
"自分の弱さに正直に | Be honest about weakness - Then train it"
"好奇心が道標 | Curiosity is the signpost - Follow interest"
"静かな自信を育てよ | Grow quiet confidence - Internal proof"
"挑戦する背中を見せよ | Show the back of a challenger - Be example"
"一貫性が信頼を生む | Consistency breeds trust - Stay aligned"
"時間に投資せよ | Invest in time - Buy the future"
"丁寧な努力は報われる | Careful effort is rewarded - Craftsmanship pays"
"努力の質を上げよ | Raise the quality of effort - Work smarter"
"やる気はやることで生まれる | Motivation is born from doing - Start first"
"挑戦に美学を | An aesthetic to challenge - Do it well"
"鍛錬は裏切らない | Training doesn’t betray - Practice pays"
"積み上げて突き抜けろ | Build up and break through - Compound to transcend"
"誠実に学び誠実に勝て | Learn sincerely, win sincerely - Fair strength"
"自分の機嫌は自分で取れ | Manage your own mood - Emotional ownership"
"志は静かに熱く | Quiet yet hot ambition - Balanced fire"
"挑戦が最大の防御 | Challenge is the best defense - Stay proactive"
"準備が不安を消す | Preparation erases anxiety - Be ready"
"一歩でも前に | Even one step forward - Micro-progress"
"今日の勝ち筋を見つけよ | Find today’s winning line - Tactics now"
"努力の蓄積が人格 | Accumulated effort forms character - Become your work"
"叱咤より自励 | Less scolding, more self-encouragement - Self-drive"
"限界は交渉可能 | Limits are negotiable - Bargain with self"
"挑戦の頻度を上げよ | Increase the frequency of challenges - More reps"
"愚直に積み上げよ | Build up earnestly - Honest repetition"
"信念は習慣で固まる | Belief is solidified by habits - Repeat conviction"
"今日も一歩 | One more step today - Keep cadence"
"努力の可視化 | Make effort visible - Track and see"
"挑戦の設計者になれ | Be the architect of your challenges - Design growth"
"誇り高く謙虚に | Proud and humble - Dual virtue"
"やれることから全力 | Go all-out on what’s doable - Control the controllable"
"足るを知り、なお進め | Know sufficiency, still advance - Grateful growth"
"逆境耐性を鍛えよ | Train adversity tolerance - Build resilience"
"挑戦は習慣 | Challenge as habit - Normalize boldness"
"結果は後からついてくる | Results follow later - Process focus"
"静かなる情熱 | Quiet passion - Consistent heat"
"努力の景色を愛せ | Love the scenery of effort - Enjoy the climb"
"志は人生の羅針盤 | Ambition is life’s compass - Navigate with purpose"
)

# Select random quote
selected_quote="${quotes[$RANDOM % ${#quotes[@]}]}"

# Print with color formatting
echo -e "\033[35m${selected_quote}\033[0m"
